[package]
name = "llang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos-derive = "0.12.1"
logos= "0.12.1"
